export const POST_MESSAGE_TYPE = {
  HTML_PAGE_REQUEST: 'HTML_PAGE_REQUEST',
  HTML_PAGE_RESPONSE: 'HTML_PAGE_RESPONSE',
  HTML_PAGE_EVENT: 'HTML_PAGE_EVENT',
  HTML_PAGE_ENABLE_COMMENT_MODE: 'HTML_PAGE_ENABLE_COMMENT_MODE',
  HTML_PAGE_DISABLE_COMMENT_MODE: 'HTML_PAGE_DISABLE_COMMENT_MODE',
  HTML_PAGE_COMMENT_MODE_ELEMENT_HOVER: 'HTML_PAGE_COMMENT_MODE_ELEMENT_HOVER',
  HTML_PAGE_COMMENT_MODE_ELEMENT_SELECTED: 'HTML_PAGE_COMMENT_MODE_ELEMENT_SELECTED',
  HTML_PAGE_COMMENT_MODE_ELEMENT_POSITION_UPDATE: 'HTML_PAGE_COMMENT_MODE_ELEMENT_POSITION_UPDATE',
  WINDOW_EVENT: 'WINDOW_EVENT',
};
